version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "WolfwithSword"
    labels:
      - "dependency"
    commit-message:
      prefix: "chore[nuget]"
      include: "scope"
    open-pull-requests-limit: 3
    pull-request-branch-name:
      separator: "-"
    ignore:
      - dependency-name: Microsoft.Extensions.Logging
        
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "WolfwithSword"
    labels:
      - "dependency"
    commit-message:
      prefix: "chore[actions]"
      include: "scope"
    open-pull-requests-limit: 3
    pull-request-branch-name:
      separator: "-"
    groups:
      updates:
        applies-to: version-updates
        patterns:
          - "*"
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"
