name: Build SubathonManager (Windows)

on:
  push:
    branches: [ main ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      upload_target:
        description: 'Artifact Storage Location'
        required: true
        default: default
        type: choice
        options:
          - default
          - github
          - nextcloud
      force_nightly:
        description: 'Force this build to create a nightly release'
        required: false
        default: 'false'
        type: boolean
jobs:

  test:
    if: github.event_name != 'pull_request' || github.actor != 'dependabot[bot]' # reconsider when more tests
    name: Run Tests & Generate Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
          
      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: nuget-${{ runner.os }}-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            nuget-${{ runner.os }}-
          
      - name: Restore dependencies
        run: dotnet restore SubathonManager.Tests/SubathonManager.Tests.csproj -p:EnableWindowsTargeting=true
        
      - name: Run tests
        run: dotnet test SubathonManager.Tests/SubathonManager.Tests.csproj \
          --configuration Release \
          --verbosity minimal --logger "console;verbosity=minimal" \
          --collect:"XPlat Code Coverage" \
          --results-directory ./coverage \
          -p:EnableWindowsTargeting=true
               
      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage/**/coverage.cobertura.xml
          fail_below_min: false
          hide_branch_rate: false
          hide_complexity: true
          indicators: false
          format: markdown
          output: both
          thresholds: '60 80'
    
  build:
    if: github.event_name != 'pull_request' || github.actor != 'dependabot[bot]'
    env:
      RUNTIME: win-x64
    name: Build Windows App
    runs-on: windows-latest
    outputs:
      artifact_failed: ${{ steps.artifact-upload.outcome != 'success' }}
      version: ${{ steps.vars.outputs.version }}
      filename: ${{ steps.vars.outputs.filename }}
      nextcloud_url: ${{ steps.nextcloud-fallback.outcome == 'success' && steps.nextcloud-fallback.outputs.SHAREABLE_URL || '' }}
      artifact_name: SubathonManager_${{env.RUNTIME}}_${{steps.vars.outputs.version}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: nuget-${{ runner.os }}-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            nuget-${{ runner.os }}-

      - name: Restore dependencies
        run: dotnet restore SubathonManager.sln

      - name: Determine version and filename
        id: vars
        shell: bash
        run: |
          RUNTIME=${{ env.RUNTIME }}
          if [ "${GITHUB_REF_NAME}" = "main" ]; then
            echo "version=nightly-${GITHUB_SHA}" >> $GITHUB_OUTPUT
          elif [ "${GITHUB_EVENT_NAME}" = "pull_request" ]; then
            echo "version=${GITHUB_SHA}" >> $GITHUB_OUTPUT
          else
            SAFE_REF=${GITHUB_REF_NAME//\//-}
            echo "version=${SAFE_REF}" >> $GITHUB_OUTPUT
          fi
          
          if [ "${GITHUB_REF_NAME}" = "main" ]; then
            echo "filename=SubathonManager_${RUNTIME}_nightly.zip" >> $GITHUB_OUTPUT
          elif [ "${GITHUB_EVENT_NAME}" = "pull_request" ]; then
            echo "filename=SubathonManager_${RUNTIME}_${GITHUB_SHA}.zip" >> $GITHUB_OUTPUT
          else
            SAFE_REF=${GITHUB_REF_NAME//\//-}
            echo "filename=SubathonManager_${RUNTIME}_${SAFE_REF}.zip" >> $GITHUB_OUTPUT
          fi
          
          if [[ "${GITHUB_REF_NAME}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            CLEAN_VERSION="${GITHUB_REF_NAME#v}"
            echo "file_version=$CLEAN_VERSION" >> $GITHUB_OUTPUT
          else
            echo "file_version=0.0.0.0" >> $GITHUB_OUTPUT
          fi

      - name: Build project
        run: >
          dotnet publish SubathonManager.UI/SubathonManager.UI.csproj 
          -c Release 
          -r ${{ env.RUNTIME }}
          --self-contained true 
          -p:PublishSingleFile=true 
          -p:IncludeAllContentForSelfExtract=true 
          -p:PublishTrimmed=false 
          -p:FileVersion=${{ steps.vars.outputs.file_version }}
          -p:AssemblyVersion=${{ steps.vars.outputs.file_version }}
          -p:InformationalVersion=${{ steps.vars.outputs.version }} 
          -o build

      - name: Copy presets folder and license into build output
        run: |
          mkdir -Force build\presets
          xcopy presets build\presets /E /I /Y
          copy LICENSE build\

      - name: Upload build artifact (GitHub)
        if: ${{ (github.event_name == 'workflow_dispatch' && (github.event.inputs.upload_target == 'github' || github.event.inputs.upload_target == 'default')) ||
          ((github.ref_type == 'tag' && github.ref != 'refs/tags/nightly') || github.ref_name == 'main') }}
        uses: actions/upload-artifact@v4
        id: artifact-upload
        continue-on-error: ${{ !(github.event_name == 'workflow_dispatch' && github.event.inputs.upload_target == 'github') }}
        with:
          name: SubathonManager_${{env.RUNTIME}}_${{steps.vars.outputs.version}}
          path: build
          retention-days: 3

      - name: Upload build artifact (Nextcloud)
        id: nextcloud-fallback
        if: ${{ github.event_name == 'pull_request'
          || (github.event_name == 'workflow_dispatch' && github.event.inputs.upload_target == 'nextcloud')
          || (steps.artifact-upload.outcome != 'success' && (github.event_name != 'workflow_dispatch' || github.event.inputs.upload_target != 'github')) }}
        uses: trympet/nextcloud-artifacts-action@v2
        continue-on-error: false
        with:
          name: SubathonManager_${{env.RUNTIME}}_${{steps.vars.outputs.version}}
          path: build
          nextcloud-url: ${{ vars.NEXTCLOUD_URL }}
          nextcloud-username: ${{ vars.NEXTCLOUD_USERNAME }}
          nextcloud-password: ${{ secrets.NEXTCLOUD_PASSWORD }}


  release:
    env:
      RUNTIME: win-x64
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    outputs:
      release_ok: ${{ steps.create_release.outcome == 'success' }}
    if: >
      (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/tags/nightly')
      || (github.ref_type == 'tag' && github.ref != 'refs/tags/nightly')
      || (github.event_name == 'push' && github.ref == 'refs/heads/main')
      || github.event.inputs.force_nightly == 'true'
    steps:
      - name: Checkout external files folder
        uses: actions/checkout@v5
        with:
          sparse-checkout: |
            external
          sparse-checkout-cone-mode: false
          
      - name: Download build artifact (GitHub)
        if: needs.build.outputs.artifact_failed == 'false' && github.event.inputs.upload_target != 'nextcloud'
        uses: actions/download-artifact@v5
        with:
          name: ${{ needs.build.outputs.artifact_name }}
          path: build/

      - name: Download build artifact (Nextcloud)
        if: needs.build.outputs.artifact_failed == 'true' && github.event.inputs.upload_target != 'github'
        run: |
          echo "Downloading release zip from Nextcloud fallback..."
          mkdir build
          curl -L "${{ needs.build.outputs.nextcloud_url }}/download?path=&files=${{ needs.build.outputs.artifact_name }}.zip" \
            -o "build/${{ needs.build.outputs.filename }}"
          mv build/${{ needs.build.outputs.filename }} ./

      - name: Zip release files
        if: needs.build.outputs.artifact_failed == 'false' && github.event.inputs.upload_target != 'nextcloud'
        run: |
          cd build
          zip -r ../${{ needs.build.outputs.filename }} .
          echo "${{ needs.build.outputs.filename }} successfully zipped"
          
      - name: Move files 
        run: |
          if [ -f "build/${{ needs.build.outputs.filename }}" ]; then
            mv build/${{ needs.build.outputs.filename }} ./
          fi
          if [ ! -f "${{ needs.build.outputs.filename }}" ]; then
            echo "ERROR: ZIP not found!"
            exit 1
          fi
          cp external/streamerbot/*.sb ./ || true
          
           
      - name: Create GitHub Release
        id: create_release
        if: startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/tags/nightly' && (github.event_name != 'workflow_dispatch' || github.event.inputs.force_nightly != 'true')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ needs.build.outputs.filename }}
            *.sb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete previous nightly asset
        if: github.ref_name == 'main' || github.event.inputs.force_nightly == 'true'
        run: |
          release_id=$(gh api repos/${{ github.repository }}/releases/tags/nightly --jq .id)
          asset_ids=$(gh api repos/${{ github.repository }}/releases/$release_id/assets --jq '.[].id')
          if [ -n "$asset_ids" ]; then
            for id in $asset_ids; do
              gh api -X DELETE repos/${{ github.repository }}/releases/assets/$id
              echo "Deleted asset $id"
            done
          else
            echo "No previous nightly assets found"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Nightly Release
        if: github.ref_name == 'main' || github.event.inputs.force_nightly == 'true'
        uses: softprops/action-gh-release@v2
        with:
          name: "Nightly Build"
          tag_name: "nightly"
          body: "Latest build from main branch."
          prerelease: true
          files: |
            ${{ needs.build.outputs.filename }}
            *.sb
          token: ${{ secrets.GITHUB_TOKEN }}

  notify:
    name: Notify Discord
    runs-on: ubuntu-latest
    needs: release
    if: startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/tags/nightly' && github.ref_name != 'main' && needs.release.outputs.release_ok == 'true'
    steps:
      - name: Fetch Release Info
        id: rel
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          api="https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ github.ref_name }}"
          response=$(curl -s -H "Authorization: Bearer $GH_TOKEN" "$api")

          RELEASE_NAME=$(echo "$response" | jq -r '.name')
          echo "release_name=$RELEASE_NAME" >> $GITHUB_OUTPUT

      - name: Send Discord Notification
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          WEBHOOK_URL_PRJ: ${{ secrets.WEBHOOK_URL_PRJ }}
        run: |
          RELEASE_URL="https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}"
          VERSION="${{ github.ref_name }}"
          ICON_URL="https://raw.githubusercontent.com/${{ github.repository }}/refs/heads/main/assets/icon.png"

          cat > payload.json <<EOF
          {
            "username": "GitHub",
            "avatar_url": "${ICON_URL}",
            "embeds": [
              {
                "title": "**SubathonManager** - ${{ steps.rel.outputs.release_name }}",
                "url": "${RELEASE_URL}",
                "description": "A new version of SubathonManager has been released!",
                "color": 5814783,
                "icon_url": "${ICON_URL}"
              }
            ]
          }
          EOF
          
          curl -X POST \
               -H "Content-Type: application/json" \
               -d @payload.json \
               "$WEBHOOK_URL"
          
          curl -X POST \
               -H "Content-Type: application/json" \
               -d @payload.json \
               "$WEBHOOK_URL_PRJ"

  update-wiki:
    if: startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/tags/nightly' && github.ref_name != 'main'
    needs: release
    uses: ./.github/workflows/wiki-drawio-upload.yml
    secrets: inherit
    with:
      release_tag: ${{ github.ref_name }}