name: Build SubathonManager (Windows)

on:
  push:
    branches: [ main ]
    tags:
        - 'v.*.*.*'
  pull_request:
    branches: [ main ]
  workflow_dispatch: 

jobs:

  build:
    if: github.event_name != 'pull_request' || github.actor != 'dependabot[bot]'
    env:
      RUNTIME: win-x64
    name: Build Windows App
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: nuget-${{ runner.os }}-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            nuget-${{ runner.os }}-

      - name: Restore dependencies
        run: dotnet restore SubathonManager.sln

      - name: Determine version and filename
        id: vars
        shell: bash
        run: |
          RUNTIME=${{ env.RUNTIME }}
          if [ "${GITHUB_REF_NAME}" = "main" ]; then
            echo "version=nightly-${GITHUB_SHA}" >> $GITHUB_OUTPUT
          elif [ "${GITHUB_EVENT_NAME}" = "pull_request" ]; then
            echo "version=${GITHUB_SHA}" >> $GITHUB_OUTPUT
          else
            echo "version=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
          fi
          
          if [ "${GITHUB_REF_NAME}" = "main" ]; then
            echo "filename=SubathonManager_${RUNTIME}_nightly.zip" >> $GITHUB_OUTPUT
          elif [ "${GITHUB_EVENT_NAME}" = "pull_request" ]; then
            echo "filename=SubathonManager_${RUNTIME}_${GITHUB_SHA}.zip" >> $GITHUB_OUTPUT
          else
            echo "filename=SubathonManager_${RUNTIME}_${GITHUB_REF_NAME}.zip" >> $GITHUB_OUTPUT
          fi

      - name: Build project
        run: >
            dotnet publish SubathonManager.UI/SubathonManager.UI.csproj 
            -c Release 
            -r ${{ env.RUNTIME }}
            --self-contained true 
            -p:PublishSingleFile=true 
            -p:IncludeAllContentForSelfExtract=true 
            -p:PublishTrimmed=false 
            -p:InformationalVersion=${{ steps.vars.outputs.version }} 
            -o build

      - name: Copy presets folder and license into build output
        run: |
          mkdir -Force build\presets
          xcopy presets build\presets /E /I /Y
          copy LICENSE build\
          
      - name: Upload build artifact
        if: ((github.ref_type == 'tag' && github.ref != 'refs/tags/nightly') || github.ref_name == 'main')
        uses: actions/upload-artifact@v4
        with:
          name: SubathonManager_${{env.RUNTIME}}_${{steps.vars.outputs.version}}
          path: build
          retention-days: 3
          
      - name: Upload build artifact (Nextcloud)
        if: ((!(github.ref_type == 'tag' && github.ref != 'refs/tags/nightly') && github.ref_name != 'main') || github.event_name == 'workflow_dispatch')
        uses: trympet/nextcloud-artifacts-action@v2
        continue-on-error: true
        with:
          name: SubathonManager_${{env.RUNTIME}}_${{steps.vars.outputs.version}}
          path: build
          nextcloud-url: ${{ secrets.NEXTCLOUD_URL }}
          nextcloud-username: ${{ secrets.NEXTCLOUD_USERNAME }}
          nextcloud-password: ${{ secrets.NEXTCLOUD_PASSWORD }}
        
  release:
    env:
      RUNTIME: win-x64
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    if: ((github.ref_type == 'tag' && github.ref != 'refs/tags/nightly') || github.ref_name == 'main') 

    steps:
      - name: Determine release filename
        id: vars
        run: |
          RUNTIME=${{env.RUNTIME}}
          
          if [ "${GITHUB_REF_NAME}" = "main" ]; then
            echo "version=nightly-${GITHUB_SHA}" >> $GITHUB_OUTPUT
          elif [ "${GITHUB_EVENT_NAME}" = "pull_request" ]; then
            echo "version=${GITHUB_SHA}" >> $GITHUB_OUTPUT
          else
            echo "version=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
          fi
          
          if [ "${GITHUB_REF_NAME}" = "main" ]; then
            echo "filename=SubathonManager_${RUNTIME}_nightly.zip" >> $GITHUB_OUTPUT
          elif [ "${GITHUB_EVENT_NAME}" = "pull_request" ]; then
            echo "filename=SubathonManager_${RUNTIME}_${GITHUB_SHA}.zip" >> $GITHUB_OUTPUT
          else
            echo "filename=SubathonManager_${RUNTIME}_${GITHUB_REF_NAME}.zip" >> $GITHUB_OUTPUT
          fi

      - name: Download build artifact
        uses: actions/download-artifact@v5
        with:
          name: SubathonManager_${{env.RUNTIME}}_${{steps.vars.outputs.version}}
          path: build/

      - name: Zip release files
        run: |
          cd build
          zip -r ../${{ steps.vars.outputs.filename }} .

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/tags/nightly'
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: ${{ steps.vars.outputs.filename }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Nightly Release
        if: github.ref_name == 'main'
        uses: softprops/action-gh-release@v2
        with:
          name: "Nightly Build"
          tag_name: "nightly"
          body: "Latest build from main branch."
          prerelease: true
          files: ${{ steps.vars.outputs.filename }}
          token: ${{ secrets.GITHUB_TOKEN }}

  notify:
    name: Notify Discord
    runs-on: ubuntu-latest
    needs: release
    if: startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/tags/nightly' && github.ref_name != 'main'
    steps:
      - name: Fetch Release Info
        id: rel
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          api="https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ github.ref_name }}"
          response=$(curl -s -H "Authorization: Bearer $GH_TOKEN" "$api")

          RELEASE_NAME=$(echo "$response" | sed -n 's/.*"name": "\(.*\)",/\1/p')

          echo "release_name=$RELEASE_NAME" >> $GITHUB_OUTPUT

      - name: Send Discord Notification
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK }}
          WEBHOOK_URL_PRJ: ${{ secrets.DISCORD_WEBHOOK_PRJ }}
        run: |
          RELEASE_URL="https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}"
          VERSION="${{ github.ref_name }}"
          ICON_URL="https://raw.githubusercontent.com/${{ github.repository }}/refs/heads/main/assets/icon.png"

          cat > payload.json <<EOF
          {
            "username": "GitHub",
            "avatar_url": "${ICON_URL}",
            "embeds": [
              {
                "title": "**SubathonManager** - New Release: ${VERSION} - ${{ steps.rel.outputs.release_name }}",
                "url": "${RELEASE_URL}",
                "description": "A new version of SubathonManager has been released!",
                "color": 5814783,
                "icon_url": "${ICON_URL}"
              }
            ]
          }
          EOF
          
          curl -X POST \
               -H "Content-Type: application/json" \
               -d @payload.json \
               "$WEBHOOK_URL"
          
          curl -X POST \
               -H "Content-Type: application/json" \
               -d @payload.json \
               "$WEBHOOK_URL_PRJ"
  update-wiki:
    # experimental
    name: Update Wiki Documentation
    runs-on: ubuntu-latest
    needs: release
      if: startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/tags/nightly'
      steps:
        - name: Check if wiki repository exists
          id: wiki-check
          run: |
            set -e
            WIKI_URL="https://github.com/${{ github.repository }}.wiki.git"

            if git ls-remote "$WIKI_URL" &>/dev/null; then
              echo "exists=true" >> $GITHUB_OUTPUT
            else
              echo "exists=false" >> $GITHUB_OUTPUT
            fi

        - name: Stop if no wiki exists
          if: steps.wiki-check.outputs.exists == 'false'
          run: echo "Wiki does not exist — skipping update."

        - name: Download draw.io file from Nextcloud
          if: steps.wiki-check.outputs.exists == 'true'
          run: |
            curl -L \
              "${{secrets.NEXTCLOUD_DRAWIO_URL}}" \
              -o "Subathon Manager.drawio"

        - name: Checkout Wiki Repository
          if: steps.wiki-check.outputs.exists == 'true'
          uses: actions/checkout@v5
          with:
            repository: ${{ github.repository }}.wiki
            token: ${{ secrets.GITHUB_TOKEN }}

        - name: Commit drawio file
          if: steps.wiki-check.outputs.exists == 'true'
          run: |
            mkdir -p docs
            cp "../Subathon Manager.drawio" "docs/Subathon Manager.drawio"

            git config user.name "github-actions"
            git config user.email "github-actions@github.com"

            git add "docs/Subathon Manager.drawio"

            if git diff --cached --quiet; then
              echo "No changes detected, skipping commit."
            else
              git commit -m "Update Subathon Manager.drawio for release ${{ github.ref_name }}"
              git push
            fi